services:
  app:
    image: ghcr.io/chenzai666/wr.do/wrdo:${TAG:-slim}
    container_name: wrdo
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/app/data/wrdo.db
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_URL: ${AUTH_URL:-http://localhost:3000}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-wr.do}
      SKIP_DB_CHECK: "false"
      SKIP_DB_MIGRATION: "false"
    volumes:
      - wrdo_data:/app/data
    networks:
      - wrdo-network
    restart: unless-stopped

volumes:
  wrdo_data:
    name: wrdo_data
    driver: local

networks:
  wrdo-network:
    driver: bridge
